export const icons = {
  house: require("./sources/house.png"),
  clock: require("./sources/clock.png"),
  settings: require("./sources/settings.png"),
  group_user: require("./sources/group-user.png"),
  chart_pie: require("./sources/chart-pie.png"),
  truck: require("./sources/truck.png"),
  clipboard_check: require("./sources/clipboard-check.png"),
  plus_circle: require("./sources/plus-circle.png"),
  followers: require("./sources/followers.png"),
  heart: require("./sources/heart.png"),
  filter: require("./sources/filter.png"),
  disconnect: require("./sources/disconnect.png"),
  arrow_down: require("./sources/arrow-down.png"),
  close: require("./sources/close.png"),
  search: require("./sources/search.png"),
  more: require("./sources/more-icon.png"),
  king: require("./sources/king.png"),
  print: require("./sources/print-icon.png"),
  receipt: require("./sources/receipt.png"),
  circle_x: require("./sources/circle-x.png"),
  message_circle: require("./sources/message-circle.png"),
  phone: require("./sources/phone.png"),
  map_pin: require("./sources/map-pin.png"),
  check: require("./sources/check.png"),
  share_2: require("./sources/share-2.png"),
  chevron_down: require("./sources/chevron-down.png"),
  shipping_step_pickup: require("./sources/shipping-step-pickup.png"),
  shipping_step_transit: require("./sources/shipping-step-transit.png"),
  shipping_step_delivering: require("./sources/shipping-step-delivering.png"),
  shipping_step_delivered: require("./sources/shipping-step-delivered.png"),
};

export type IconsTypes = keyof typeof icons;
