import { StyleSheet } from "react-native";
import { createStyles } from "@utils/createStyles";

export const shippingSettingsStyles = createStyles(({ colors }) => ({
  safeArea: { flex: 1, backgroundColor: colors.neutral100 },
  header: {
    minHeight: 72,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.neutral100,
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.neutral50,
    alignItems: "center",
    justifyContent: "center",
  },
  backIcon: {
    color: colors.neutral900,
    fontSize: 34,
    lineHeight: 34,
    marginTop: -4,
  },
  headerIcon: { width: 20, height: 20, tintColor: colors.neutral900 },
  title: {
    flex: 1,
    marginHorizontal: 12,
    color: colors.neutral900,
    textAlign: "center",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "500",
  },
  scrollContent: { paddingBottom: 32 },
  section: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 20, gap: 16 },
  sectionTitle: {
    color: colors.neutral900,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500",
  },
  warehouseCard: {
    borderRadius: 16,
    borderWidth: 0.5,
    borderColor: colors.border10,
    backgroundColor: colors.neutral50,
    padding: 16,
    columnGap: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  emptyWarehouseCard: {
    minHeight: 116,
    borderRadius: 16,
    borderWidth: 0.5,
    borderColor: colors.border10,
    backgroundColor: colors.neutral50,
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  emptyWarehouseTitle: {
    color: colors.neutral900,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "500",
  },
  emptyWarehouseText: {
    color: colors.neutral400,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  warehouseHeader: {
    flex: 1,
    flexGrow: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  storeIconBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.neutral100,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
  },
  storeIcon: { color: colors.neutral900, fontSize: 18, lineHeight: 22 },
  storeNameWrap: { flex: 1, minWidth: 0, gap: 2 },
  storeName: {
    color: colors.neutral900,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500",
  },
  storeDefaultText: { color: colors.neutral400, fontSize: 12, lineHeight: 18 },
  editIcon: { color: colors.neutral900, fontSize: 16, lineHeight: 18 },
  editText: {
    color: colors.neutral900,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "500",
  },
  warehouseMeta: { gap: 8 },
  infoLine: { flexDirection: "row", alignItems: "center", gap: 8 },
  infoIcon: {
    width: 16,
    color: colors.neutral400,
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  infoText: { flex: 1, color: colors.neutral400, fontSize: 12, lineHeight: 18 },
  addButton: {
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: colors.border20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  addIcon: { color: colors.neutral400, fontSize: 18, lineHeight: 22 },
  addText: { color: colors.neutral400, fontSize: 14, lineHeight: 22 },
  breakLine: { height: 8, backgroundColor: colors.neutral50 },
  partnerSection: { paddingHorizontal: 16, paddingVertical: 20, gap: 20 },
  partnerGroup: { gap: 16 },
  partnerGroupTitle: { color: colors.neutral500, fontSize: 14, lineHeight: 22 },
  partnerList: { gap: 12 },
  partnerCard: {
    borderRadius: 16,
    backgroundColor: colors.neutral50,
    paddingLeft: 16,
    paddingRight: 12,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  partnerContent: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
  },
  deliveryLogo: {
    width: 44,
    height: 44,
    borderRadius: 12,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  deliveryLogoImage: { width: 30, height: 30 },
  partnerTextWrap: { flex: 1, minWidth: 0, gap: 4 },
  partnerTitleRow: {
    maxWidth: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  partnerName: {
    flexShrink: 1,
    color: colors.neutral900,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "500",
  },
  defaultTag: {
    height: 24,
    borderRadius: 16,
    backgroundColor: colors.neutral100,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  defaultText: {
    color: colors.neutral500,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
  },
  comingSoonTag: {
    height: 24,
    borderRadius: 16,
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  comingSoonText: {
    color: "#6B7280",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
  },
  partnerDescription: {
    color: colors.neutral400,
    fontSize: 12,
    lineHeight: 18,
  },
  chevron: {
    color: colors.neutral900,
    fontSize: 24,
    lineHeight: 24,
    transform: [{ rotate: "180deg" }],
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  modalCard: {
    maxHeight: "88%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.neutral100,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    overflow: "hidden",
  },
  modalPageCard: {
    flex: 1,
    maxHeight: "100%",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  modalTitle: {
    color: colors.neutral900,
    fontSize: 18,
    lineHeight: 26,
    fontWeight: "600",
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.neutral50,
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseText: { color: colors.neutral900, fontSize: 24, lineHeight: 28 },
  modalContent: { paddingTop: 20, paddingBottom: 16, gap: 14 },
  inputGroup: { gap: 8 },
  inputLabel: {
    color: "#111827",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  requiredMark: { color: "#ef4444" },
  addressLabelRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  newAddressTag: {
    borderRadius: 4,
    backgroundColor: "#dbeafe",
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  newAddressTagText: {
    color: "#3b82f6",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "500",
  },
  input: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: colors.neutral100,
    paddingHorizontal: 12,
    color: colors.neutral900,
    fontSize: 14,
    lineHeight: 20,
  },
  inputError: { borderColor: "#ef4444" },
  textArea: {
    minHeight: 92,
    paddingTop: 10,
    paddingBottom: 10,
    textAlignVertical: "top",
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  switchTextWrap: { flex: 1, gap: 2 },
  switchTitle: {
    color: "#111827",
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "600",
  },
  switchSubtitle: { color: "#9ca3af", fontSize: 12, lineHeight: 18 },
  switchTrack: {
    width: 44,
    height: 24,
    borderRadius: 24,
    justifyContent: "center",
  },
  switchTrackActive: { backgroundColor: "#ebb140" },
  switchTrackInactive: { backgroundColor: "#e5e7eb" },
  switchThumb: {
    position: "absolute",
    top: 2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.neutral100,
  },
  switchThumbActive: { right: 2 },
  switchThumbInactive: { left: 2 },
  pickerButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: colors.neutral100,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  pickerButtonDisabled: { opacity: 0.5 },
  pickerButtonText: {
    flex: 1,
    color: colors.neutral900,
    fontSize: 14,
    lineHeight: 20,
  },
  pickerPlaceholder: { color: "#d1d5db" },
  pickerChevron: { color: "#9ca3af", fontSize: 18, lineHeight: 22 },
  formErrorBox: {
    borderRadius: 8,
    backgroundColor: "#fef2f2",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  formErrorText: { color: "#ef4444", fontSize: 13, lineHeight: 18 },
  saveButton: {
    height: 50,
    borderRadius: 8,
    backgroundColor: "#ebb140",
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonDisabled: { opacity: 0.65 },
  saveButtonText: {
    color: colors.neutral100,
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "700",
    letterSpacing: 0.7,
  },
  geoPickerOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.35)",
    zIndex: 10,
  },
  geoPickerCard: {
    maxHeight: "82%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.neutral100,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
  },
  geoSearchInput: {
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: colors.neutral100,
    marginTop: 16,
    paddingHorizontal: 12,
    color: colors.neutral900,
    fontSize: 14,
    lineHeight: 20,
  },
  geoListContent: { paddingTop: 12, paddingBottom: 8 },
  geoItem: {
    minHeight: 46,
    borderRadius: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  geoItemSelected: { backgroundColor: "#fff7e6" },
  geoItemText: { flex: 1, color: "#111827", fontSize: 14, lineHeight: 22 },
  geoItemTextSelected: { color: "#c47f00", fontWeight: "600" },
  geoSelectedIcon: {
    color: "#ebb140",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
}));
