import { createStyles } from "@utils/createStyles";

export const shipmentStyles = createStyles(() => ({
  sectionBlock: { paddingHorizontal: 16, paddingVertical: 18, gap: 14 },
  sectionHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
  },
  addressCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    gap: 12,
    minHeight: 108,
    justifyContent: "center" as const,
  },
  addAddressCard: {
    height: 76,
    borderWidth: 1,
    borderStyle: "dashed" as const,
    borderRadius: 16,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 10,
  },
  addCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  addressTopRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  addressInfo: { flex: 1, gap: 4 },
  addressNameRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  addressName: { flexShrink: 1 },
  changePill: {
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  defaultBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  addressLine: { lineHeight: 22 },
  divider: { height: 8 },
  orderCard: { borderRadius: 16, padding: 14, gap: 12 },
  orderMetaRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    gap: 12,
  },
  productTitle: { flex: 1 },
  detailGrid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
  },
  detailCell: { width: "48%" as const, borderRadius: 12, padding: 12, gap: 4 },
  quantityRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
  },
  stepper: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    borderRadius: 18,
    overflow: "hidden" as const,
  },
  stepperBtn: {
    width: 36,
    height: 36,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  stepperValue: { minWidth: 42, textAlign: "center" as const },
  moneyFieldWrap: { gap: 8 },
  moneyField: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
  },
  moneyInput: { flex: 1, padding: 0 },
  optionGrid: { gap: 10 },
  optionChip: {
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
  },
  optionDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  optionDotInner: { width: 8, height: 8, borderRadius: 4 },
  selectTrigger: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
    marginTop: 8,
  },
  selectOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "flex-end" as const,
  },
  selectDropdown: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderBottomWidth: 0,
    maxHeight: 400,
  },
  selectCloseRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  selectItem: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  noteInput: {
    minHeight: 96,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    textAlignVertical: "top" as const,
  },
  formGroup: { gap: 6 },
  fieldLabel: { fontSize: 12, lineHeight: 18 },
  textInput: {
    height: 48,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
  },
  feeBox: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 44,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  feeBoxRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    width: "100%" as const,
  },
  summaryRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
  },
  sheetOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)" },
  sheetContainer: {
    position: "absolute" as const,
    bottom: 0,
    left: 0,
    right: 0,
  },
  sheetPanel: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 12,
    maxHeight: 520,
    gap: 16,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#E5E5E5",
    alignSelf: "center" as const,
    marginBottom: 4,
  },
  sheetTitle: { textAlign: "center" as const, marginBottom: 4 },
  sheetFooter: { flexDirection: "row" as const, gap: 12, paddingTop: 8 },
  sheetCancelBtn: {
    flex: 1,
    height: 52,
    borderWidth: 1,
    borderRadius: 16,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  sheetSaveBtn: {
    flex: 2,
    height: 52,
    borderRadius: 16,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  dimRow: { flexDirection: "row" as const, gap: 10 },
  dimField: { flex: 1, gap: 6 },
  dimAutoScaleRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
    marginTop: 12,
    paddingVertical: 8,
  },
  dimCheckbox: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderRadius: 4,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  voucherCard: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 44,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
    marginTop: 8,
  },
  voucherCardInfo: { flex: 1, gap: 2 },
  moneyInputRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    height: 48,
    borderWidth: 1,
    borderRadius: 12,
    overflow: "hidden" as const,
  },
  moneyInputInner: { flex: 1, paddingHorizontal: 14, height: "100%" as const },
  moneyInputSuffix: {
    paddingHorizontal: 12,
    height: "100%" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderLeftWidth: 1,
  },
}));
