import { StyleSheet } from "react-native";

export const printerSettingsStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fff" },
  header: {
    minHeight: 72,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
  },
  headerButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#f2f2f2",
    alignItems: "center",
    justifyContent: "center",
  },
  backIcon: { color: "#000", fontSize: 34, lineHeight: 34, marginTop: -4 },
  headerPlaceholder: { width: 44, height: 44, opacity: 0 },
  title: {
    flex: 1,
    marginHorizontal: 12,
    color: "#000",
    textAlign: "center",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "500",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 32,
    gap: 16,
  },

  // Notice card
  noticeCard: {
    borderRadius: 12,
    backgroundColor: "#fdedd3",
    paddingLeft: 16,
    paddingRight: 12,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  noticeIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#2b2b2b",
    color: "#2b2b2b",
    textAlign: "center",
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "600",
  },
  noticeText: { flex: 1, color: "#2b2b2b", fontSize: 12, lineHeight: 18 },

  // Connection card
  card: {
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(0,0,0,0.1)",
    backgroundColor: "#f2f2f2",
    padding: 16,
    gap: 16,
  },
  row: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  rowStacked: { minHeight: 44 },
  rowTextWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  rowTextStacked: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 4,
  },
  rowLabel: { color: "#484848", fontSize: 12, lineHeight: 18 },
  rowValue: { color: "#000", fontSize: 14, lineHeight: 22, fontWeight: "500" },
  chevron: {
    color: "#000",
    fontSize: 24,
    lineHeight: 24,
    transform: [{ rotate: "180deg" }],
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(0,0,0,0.1)",
  },

  // Test button
  testButton: {
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  testButtonText: { color: "#000", fontSize: 14, lineHeight: 22, fontWeight: "500" },
  testButtonDisabled: { opacity: 0.5 },

  // Template list
  templateList: { gap: 0 },
  templateRow: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  templateLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  templateIcon: { width: 24, height: 24, tintColor: "#000" },
  templateText: { flex: 1, color: "#000", fontSize: 14, lineHeight: 22 },
  templateDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(0,0,0,0.1)",
    marginVertical: 16,
  },

  // Option picker sheet
  sheetBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  sheetCard: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
    gap: 8,
  },
  sheetTitle: {
    color: "#000",
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "600",
    marginBottom: 8,
  },
  sheetOption: {
    minHeight: 48,
    borderRadius: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sheetOptionSelected: { backgroundColor: "#fff7e6" },
  sheetOptionText: { flex: 1, color: "#111827", fontSize: 14, lineHeight: 22 },
  sheetOptionTextSelected: { color: "#c47f00", fontWeight: "600" },
  sheetSelectedMark: { color: "#ebb140", fontSize: 16, lineHeight: 20, fontWeight: "700" },

  // IP input
  ipInputContainer: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  ipInput: {
    flex: 1,
    color: "#000",
    fontSize: 14,
    lineHeight: 22,
    fontWeight: "500",
    padding: 0,
  },
});
